name : coupon2
channels :
 - anaconda
 - conda-forge
 - defaults 
dependencies:
 - pip=21.1.3
 - python=3.8
 - numpy=1.19.5
 - pandas=1.1.5
 - pip:
   - scipy==1.5.4
   - mlflow==1.25.1
   - fastparquet==0.8.1
   - pyarrow==8.0.0
   - Sphinx==4.5.0