name : coupon2
channels :
 - anaconda
 - conda-forge
 - defaults 
dependencies:
 - pip=21.1.3
 - python=3.8.10
 - numpy=1.19.5
 - pandas=1.1.5
 - scikit-learn=0.23.2
 - mlxtend=0.19.0
 - statsmodels=0.12.2
 - imbalanced-learn=0.7.0
 - lightgbm==3.3.1
 - pip:
   - scipy==1.5.4
   - mlflow==1.26.1
   - fastparquet==0.8.1
   - pyarrow==8.0.0
   - sphinx==4.3.1
   - sphinx-autobuild==0.7.1
   - sphinx-inline-tabs==2021.4.11b9
   - python-docs-theme==2021.5
   - sphinx-copybutton==0.4.0
   - python-dotenv==0.20.0
   - optuna==2.10.0